# Generated by Django 3.2.7 on 2021-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210904_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
