# Generated by Django 3.2.7 on 2021-09-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eng_title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(help_text='Say what you want to do with your study or jub partner.', max_length=500, verbose_name='Summary and indeas')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(choices=[(2, 'فقط ۲ نفر'), (5, '۳ تا ۵ نفر'), (10, '۵ تا ۱۰ نفر')])),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, through='squads.Membership', to='profiles.Profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad'),
        ),
        migrations.AddField(
            model_name='membership',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(help_text='Say about your activities', max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
