# Generated by Django 3.2.7 on 2021-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='groups_pictures/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(help_text='درباره کارهایی که کردید بنویسید', max_length=300, verbose_name='گزارش فعالیت'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='capacity',
            field=models.IntegerField(choices=[(2, 'فقط ۲ نفر'), (5, '۳ تا ۵ نفر'), (10, '۵ تا ۱۰ نفر')], verbose_name='حداکثر ظرفیت گروه'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='eng_title',
            field=models.CharField(help_text='این قراره آدرس گروهتون باشه: \n bahamkhan.ir/group/example', max_length=100, unique=True, verbose_name='تایتل انگلیسی گروه'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم گروه'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='summary',
            field=models.TextField(help_text='خلاصه اهداف گروه و کارهایی که قصد دارید تو گروه بکنید رو اینجا بنویسید.', max_length=500, verbose_name='توضیحات گروه'),
        ),
    ]
