# Generated by Django 3.2.7 on 2021-09-06 15:42

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0004_auto_20210906_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='is_shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='squad',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='groups_pictures'),
        ),
    ]
