# Generated by Django 3.2.7 on 2021-09-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0005_auto_20210906_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad',
            old_name='is_shown',
            new_name='show_comments',
        ),
    ]
