# Generated by Django 3.2.7 on 2021-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0006_rename_is_shown_squad_show_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
