# Generated by Django 3.2.7 on 2021-09-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0007_membership_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad',
            name='show_comments',
            field=models.BooleanField(default=True, verbose_name='نمایش کامنت\u200cهای برای کاربران غیر عضو'),
        ),
        migrations.AlterField(
            model_name='squad',
            name='summary',
            field=models.TextField(help_text='خلاصه اهداف گروه و کارهایی که قصد دارید تو گروه بکنید رو اینجا بنویسید.', max_length=255, verbose_name='توضیحات گروه'),
        ),
    ]
